---
.travis.yml:
  secure: "g77bF8nhzpi2zvqeyMb1smOWeSynjIT7YHz5wpElZ7vbFQXwwqwUgmkqxjVWt8ntjdZsEj/mvahYSIA9rOKW1Y/LBYatDIPn4JIZWn0JtlcCcQbLQJhBuA/g+8vjhCzIV1Pf1TRVcGyhH2TvJghhbBefbU9fmkYE89TFQF42LHw="
#spec/spec_helper_acceptance.rb:
# Temporarily unmanage spec_helper_acceptance (iss. #133)
#  windows: true
#  dependencies:
#    - puppetlabs-stdlib
